language: python
python:
  - "3.5"
# command to run tests, e.g. python setup.py test
before_install: bash travis_setup.sh
before_script:
  - export PATH=$PATH:$HOME/bin
  - git lfs pull
script: bash travis_tests.sh
notifications:
  email:
    - grahame@angrygoats.net
